### ISSUE TITLE
Pre-commit hook fails

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#366]
```
yarn run v1.22.22
$ tsc
Done in 5.23s.
yarn run v1.22.22
$ /Users/ilyabeda/projects/beda/fhir-emr/node_modules/.bin/lint-staged
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc — 2 files
[STARTED] *.{js,jsx,ts,tsx} — 1 file
[STARTED] eslint --fix
[FAILED] eslint --fix [FAILED]
[FAILED] eslint --fix [FAILED]
[FAILED] eslint --fix [FAILED]
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...

✖ eslint --fix:

Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: Failed to load plugin 'storybook' declared in '.eslintrc.cjs': Class extends value undefined is not a constructor or null
Referenced from: /Users/ilyabeda/projects/beda/fhir-emr/.eslintrc.cjs
    at Object.<anonymous> (/Users/ilyabeda/projects/beda/fhir-emr/node_modules/eslint-plugin-storybook/node_modules/@typescript-eslint/utils/dist/ts-eslint/eslint/LegacyESLint.js:12:51)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/ilyabeda/projects/beda/fhir-emr/node_modules/eslint-plugin-storybook/node_modules/@typescript-eslint/utils/dist/ts-eslint/ESLint.js:8:22)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)
```

**Comment by ruscoder** [comment]
@ir4y Maybe it's outdated, please double check on master branch with deleting all node modules and close if it's not relevant

**Comment by ir4y** [comment]
It happened when there is a change in storybook
